openapi: 3.1.0
info:
  title: Pseudoniemen Service (@git.commit.id.abbrev@)
  description: See [PseudoniemenService](https://github.com/ICTU/pseudoniemenservice/commit/@git.commit.id@)
  version: 0.1.0
servers:
  - url: /v1
paths:
  /getToken:
    post:
      tags:
        - Token
      summary: get a token
      operationId: getToken
      parameters:
        - $ref: "#/components/parameters/callerOIN"
      requestBody:
        $ref: '#/components/requestBodies/getTokenRequest'
      responses:
        '200':
          $ref: '#/components/responses/getTokenResponse'
  /exchangeToken:
    post:
      tags:
        - Token
        - Identifier
      summary: exchange token for an identifier
      operationId: exchangeToken
      parameters:
        - $ref: "#/components/parameters/callerOIN"
      requestBody:
        $ref: '#/components/requestBodies/exchangeTokenRequest'
      responses:
        '200':
          $ref: '#/components/responses/exchangeTokenResponse'
  /exchangeIdentifier:
    post:
      tags:
        - Identifier
      summary: exchange an identifier for another identifier
      operationId: exchangeIdentifier
      parameters:
        - $ref: "#/components/parameters/callerOIN"
      requestBody:
        $ref: '#/components/requestBodies/exchangeIdentifierRequest'
      responses:
        '200':
          $ref: '#/components/responses/exchangeIdentifierResponse'
components:
  parameters:
    callerOIN:
      name: callerOIN
      in: header
      required: true
      schema:
        $ref: '#/components/schemas/oin'
  schemas:
    scope:
      type: object
    token:
      nullable: false
      type: string
    oin:
      nullable: false
      type: string
      pattern: '^\d{20}$'
      minLength: 20
      maxLength: 20
      example: 12340123401234012340
    identifier:
      nullable: false
      type: object
      properties:
        value:
          type: string
        type:
          $ref: '#/components/schemas/identifierTypes'
    identifierTypes:
      nullable: false
      type: string
      enum:
        - BSN
        - ORGANISATION_PSEUDO
    getTokenResponse:
      nullable: false
      type: object
      properties:
        token:
          $ref: '#/components/schemas/token'
    exchangeTokenResponse:
      nullable: false
      type: object
      properties:
        identifier:
          $ref: '#/components/schemas/identifier'
    exchangeIdentifierResponse:
      nullable: false
      type: object
      properties:
        identifier:
          $ref: '#/components/schemas/identifier'
  responses:
    getTokenResponse:
      description: Get a token Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/getTokenResponse'
    exchangeTokenResponse:
      description: successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/exchangeTokenResponse'
    exchangeIdentifierResponse:
      description: successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/exchangeIdentifierResponse'
  requestBodies:
    getTokenRequest:
      required: true
      content:
        application/json:
          schema:
            properties:
              identifier:
                $ref: '#/components/schemas/identifier'
              recipientOIN:
                $ref: '#/components/schemas/oin'
              scope:
                $ref: '#/components/schemas/scope'
    exchangeTokenRequest:
      required: true
      content:
        application/json:
          schema:
            properties:
              token:
                $ref: '#/components/schemas/token'
              identifierType:
                $ref: '#/components/schemas/identifierTypes'
              scope:
                $ref: '#/components/schemas/scope'
    exchangeIdentifierRequest:
      required: true
      content:
        application/json:
          schema:
            properties:
              identifier:
                $ref: '#/components/schemas/identifier'
              recipientOIN:
                $ref: '#/components/schemas/oin'
              recipientIdentifierType:
                $ref: '#/components/schemas/identifierTypes'
              scope:
                $ref: '#/components/schemas/scope'
