openapi: 3.0.3
info:
  title: Pseudoniemen Service (@git.commit.id.abbrev@)
  description: See [PseudoniemenService](https://github.com/ICTU/pseudoniemenservice/commit/@git.commit.id@)
  version: 0.1.0
servers:
  - url: /v1
paths:
  /getToken:
    post:
      summary: get a token
      operationId: getToken
      parameters:
        - $ref: "#/components/parameters/callerOIN"
      requestBody:
        $ref: '#/components/requestBodies/getTokenRequest'
      responses:
        '200':
          $ref: '#/components/responses/getTokenResponse'
  /exchangeToken:
    post:
      summary: excgange token for an identifier
      operationId: exchangeTokenForIdentifier
      parameters:
        - $ref: "#/components/parameters/callerOIN"
      requestBody:
        $ref: '#/components/requestBodies/exchangeTokenRequest'
      responses:
        '200':
          $ref: '#/components/responses/exchangeTokenResponse'
  /exchangeIdentifier:
    post:
      summary: exchange an identifier for another identifier
      operationId: exchangeIdentifierForIdentifier
      parameters:
        - $ref: "#/components/parameters/callerOIN"
      requestBody:
        $ref: '#/components/requestBodies/exchangeIdentifierRequest'
      responses:
        '200':
          $ref: '#/components/responses/exchangeIdentifierResponse'
components:
  parameters:
    callerOIN:
      name: callerOIN
      in: header
      required: true
      schema:
        $ref: '#/components/schemas/oin'
  schemas:
    token:
      type: string
    oin:
      type: string
      pattern: '^\d{20}$'
      minLength: 20
      maxLength: 20
    identifier:
      type: object
      properties:
        value:
          type: string
        type:
          $ref: '#/components/schemas/identifierTypes'
    identifierTypes:
      type: string
      nullable: false
      enum:
        - BSN
        - ORGANISATION_PSEUDO
  responses:
    getTokenResponse:
      description: Get a token Response
      content:
        application/json:
          schema:
            properties:
              token:
                $ref: '#/components/schemas/token'
    exchangeTokenResponse:
      description: successful operation
      content:
        application/json:
          schema:
            properties:
              identifier:
                $ref: '#/components/schemas/identifier'
    exchangeIdentifierResponse:
      description: successful operation
      content:
        application/json:
          schema:
            properties:
              identifier:
                $ref: '#/components/schemas/identifier'
  requestBodies:
    getTokenRequest:
      required: true
      content:
        application/json:
          schema:
            properties:
              identifier:
                $ref: '#/components/schemas/identifier'
              recipientOIN:
                $ref: '#/components/schemas/oin'
    exchangeTokenRequest:
      required: true
      content:
        application/json:
          schema:
            properties:
              token:
                $ref: '#/components/schemas/token'
              identifierType:
                $ref: '#/components/schemas/identifierTypes'
    exchangeIdentifierRequest:
      required: true
      content:
        application/json:
          schema:
            properties:
              identifier:
                $ref: '#/components/schemas/identifier'
              recipientOIN:
                $ref: '#/components/schemas/oin'
              recipientIdentifierType:
                $ref: '#/components/schemas/identifierTypes'
