server:
  mime-mappings:
    yaml: application/json
  compression:
    enabled: true
  forward-headers-strategy: framework
logging:
  level:
    ROOT: info
    nl.ictu: debug
spring:
  web:
    resources:
      cache:
        cachecontrol:
          must-revalidate: true
          max-age: 15m
          no-cache: true
  application:
    name: Pseudoniemen Service
  jackson:
    time-zone: Europe/Amsterdam

management:
  server:
    port: 9080
  endpoints:
    web:
      exposure:
        include: 'health, info'
