server:
  mime-mappings:
    yaml: application/json
  compression:
    enabled: true
  forward-headers-strategy: framework
logging:
  level:
    ROOT: info
    nl.appsource: debug
spring:
  web:
    resources:
      cache:
        cachecontrol:
          must-revalidate: true
          max-age: 15m
          no-cache: true
  application:
    name: Pseudoniemen Service
  jackson:
    time-zone: Europe/Amsterdam

management:
  endpoint:
    info:
      access: read_only
    health:
      access: read_only
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure:
        include:
          - health
          - info
  server:
    port: 9080
    ssl:
      enabled: false
    add-application-context-header: true