server:
  compression:
    enabled: true
  forward-headers-strategy: framework
logging:
  level:
    ROOT: info
    nl.appsource: debug
spring:
  application:
    name: Pseudoniemen Service
management:
  endpoint:
    info:
      access: read_only
    health:
      access: read_only
      probes:
        enabled: true