openapi: 3.0.3
info:
  title: Pseudoniemen Service
  version: 0.1.0
servers:
  - url: http://localhost/v1
paths:
  /getToken:
    post:
      summary: get a token
      operationId: getToken
      requestBody:
        $ref: '#/components/requestBodies/getTokenRequest'
      responses:
        '200':
          $ref: '#/components/responses/getTokenResponse'
  /exchangeToken:
    post:
      summary: get an identifier
      operationId: exchangeTokenForIdentifier
      requestBody:
        $ref: '#/components/requestBodies/exchangeTokenRequest'
      responses:
        '200':
          $ref: '#/components/responses/exchangeTokenResponse'
  /exchangeIdentifier:
    post:
      summary: get an identifier
      operationId: exchangeIdentifierForIdentifier
      requestBody:
        $ref: '#/components/requestBodies/exchangeIdentifierRequest'
      responses:
        '200':
          $ref: '#/components/responses/exchangeIdentifierResponse'
components:
  schemas:
    token:
      type: string
    oin:
      type: string
      pattern: '^\d{20}$'
      minLength: 20
      maxLength: 20
    identifier:
      type: object
      properties:
        identifierValue:
          type: string
        identifierType:
          $ref: '#/components/schemas/identifierTypes'
    identifierTypes:
      type: string
      nullable: false
      enum:
        - BSN
        - SECTOR_PSEUDO
        - ORGANISATION_PSEUDO
  responses:
    getTokenResponse:
      description: Get a token Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/token'
    exchangeTokenResponse:
      description: successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/identifier'
    exchangeIdentifierResponse:
      description: successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/identifier'
  requestBodies:
    getTokenRequest:
      required: true
      content:
        application/json:
          schema:
            properties:
              identifier:
                $ref: '#/components/schemas/identifier'
              oin:
                $ref: '#/components/schemas/oin'
    exchangeTokenRequest:
      required: true
      content:
        application/json:
          schema:
            properties:
              token:
                $ref: '#/components/schemas/token'
              identifierType:
                $ref: '#/components/schemas/identifierTypes'
    exchangeIdentifierRequest:
      required: true
      content:
        application/json:
          schema:
            properties:
              identifier:
                $ref: '#/components/schemas/identifier'
              oin:
                $ref: '#/components/schemas/oin'
