name: Build Image

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: "liberica"
          cache: maven

      - name: Build with Maven
        run: mvn -ntp -B spring-boot:build-image
